sudo: false
language: ruby
rvm:
  - 2.3
  - 2.4
  - 2.5
  - 2.6
before_install:
  - gem update --system
  - gem uninstall -v '>= 2' -i $(rvm gemdir)@global -ax bundler || true
  - gem install bundler -v '< 2'
gemfile:
  - gemfiles/mail_2.7.gemfile
  - gemfiles/mail_2.7.0.gemfile
  - gemfiles/mail_2.6.gemfile
